# name: github-page
# on:
#   push:
#     branches:
#       - dev

# jobs:
#  github-pages:
#     runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统
#     steps:
#     - name: checkout
#       uses: actions/checkout@master # 将代码拷贝到虚机中
  
#     - name: Get yarn cache
#       id: yarn-cache
#       run: echo "::set-output name=dir::$(yarn cache dir)"

#     - uses: actions/cache@v1
#       with:
#         path: ${{ steps.yarn-cache.outputs.dir }}
#         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
#         restore-keys: |
#           ${{ runner.os }}-yarn-
      
#     - name: Build and Deploy
#       uses: JamesIves/github-pages-deploy-action@master 
#       env:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # 使用刚新建的secret
#         BRANCH: gh-pages # 存放产物的分支名称
#         FOLDER: dist # 存放build后产物的目录
#         BASE_BRANCH: dev
#         BUILD_SCRIPT: yarn install && yarn run github # 执行的命令
