name: actions test
on:
  push:
    branches:
      - dev

jobs:
 test:
    runs-on: ubuntu-latest # 我们选择使用最新的ubuntu系统

    steps:
      - uses: actions/checkout@v1 # 将代码拷贝到虚机中
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      
      - name: cache
        run: yarn cache list

      - name: install
        run: yarn install

      - name: build
        run: yarn run github

      - name: init-repository
        env: 
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          cd dist
          git init
          git config user.name moreant
          git config user.email 552191481@qq.com
          git remote add origin git@github.com:moreant/yeek-vue.git
          git checkout -b gh-pages
          git add --all .
          git commit -m "pages"
          git push origin gh-pages --force




